version: "3"

services:
  webapi:
    build: docker/fastapi
    container_name: fastapi
    # ports:
    #   - 80:8000
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - backend

  ssl-lb:
    image: arm64v8/haproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html
    networks:
      - backend
    depends_on:
      - webapi
  
  certbot:
    image: certbot/certbot:arm64v8-latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: ["--version"]
  

networks:
  backend:

  
    